# -*- coding: utf-8 -*-
"""Copy of centaur_8b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZASYtYZbJJft8hO4ZGUuDwOxW9lV6w7
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import os, re
# if "COLAB_" not in "".join(os.environ.keys()):
#     !pip install unsloth
# else:
#     # Do this only in Colab notebooks! Otherwise use pip install unsloth
#     import torch; v = re.match(r"[0-9\.]{3,}", str(torch.__version__)).group(0)
#     xformers = "xformers==" + ("0.0.32.post2" if v == "2.8.0" else "0.0.29.post3")
#     !pip install --no-deps bitsandbytes accelerate {xformers} peft trl triton cut_cross_entropy unsloth_zoo
#     !pip install sentencepiece protobuf "datasets>=3.4.1,<4.0.0" "huggingface_hub>=0.34.0" hf_transfer
#     !pip install --no-deps unsloth
# !pip install transformers==4.55.4
# !pip install --no-deps trl==0.22.2

from unsloth import FastLanguageModel
import transformers

### LLM ###
model, tokenizer = FastLanguageModel.from_pretrained(
  model_name = "marcelbinz/Llama-3.1-Minitaur-8B-adapter",
  max_seq_length = 32768,
  dtype = None,
  load_in_4bit = True,
)
FastLanguageModel.for_inference(model)

pipe = transformers.pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            trust_remote_code=True,
            pad_token_id=0,
            do_sample=True,
            temperature=1.0,
            max_new_tokens=1,
)

prompt = "You will see a target line and three comparison lines labeled A, B, and C.\n" \
  "In each trial, press the key for the line that matches the target in length.\n\n" \
  "Target: medium. A: medium, B: long, C: short. Others say: B B B B B B. You press <<A>>.\n" \
  "Target: short. A: long, B: short, C: medium. Others say: B B B B B B. You press <<B>>.\n" \
  "Target: long. A: long, B: short, C: medium. Others say: C C C C C C. You press <<A>>.\n" \
  "Target: medium. A: medium, B: long, C: short. Others say: B B B B B B. You press <<B>>.\n" \
  "Target: short. A: short, B: medium, C: long. Others say: C C C C C C. You press <<"

print(prompt)

choice = pipe(prompt)[0]['generated_text'][len(prompt):]
print(choice)

